=== mattman-ps/systemchecks/example/schema/system_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "systemName"
  ],
  "properties": {
    "systemName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "FilesExist": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "filePath"
        ],
        "properties": {
          "friendlyName": {
            "type": "string"
          },
          "filePath": {
            "type": "string"
          }
        }
      }
    },
    "Processes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "friendlyName": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      }
    },
    "Services": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "friendlyName": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      }
    },
    "URIs": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "uri"
        ],
        "properties": {
          "friendlyName": {
            "type": "string"
          },
          "uri": {
            "type": "string"
          },
          "useBasicParsing": {
            "type": "boolean"
          },
          "useDefaultCredentials": {
            "type": "boolean"
          }
        }
      }
    },
    "ScheduledTasks": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "taskpath"
        ],
        "properties": {
          "friendlyName": {
            "type": "string"
          },
          "taskpath": {
            "type": "string"
          }
        }
      }
    },
    "SharesExist": {
      "type": "array",
      "items": {
        "required": [
          "SharePath"
        ],
        "properties": {
          "friendlyName": {
            "type": "string"
          },
          "SharePath": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== mattman-ps/systemchecks/example/example-1.json
{
	"$schema": "https://cdn.jsdelivr.net/gh/mattman-ps/systemchecks@v0.3.0/example/schema/system_schema.json",
	"systemName": "MattMan's Special System",
	"description": "This is a sample system",
	"FilesExist": [
		{
			"friendlyName": "Check for hosts file",
			"filePath": "C:/windows/System32/drivers/etc/hosts"
		}
	],
	"Processes": [
		{
			"friendlyName": "Microsoft OneDrive",
			"name": "OneDrive"
		},
		{
			"friendlyName": "WindowsPackageManagerServer.exe",
			"name": "WindowsPackageManagerServer"
		}
	],
	"Services": [
		{
			"friendlyName": "World Wide Web Publishing Service",
			"name": "w3svc"
		},
		{
			"friendlyName": "Background Intelligent Transfer Service",
			"name": "BITS"
		}
	],
	"URIs": [
		{
			"friendlyName": "Gitea Server",
			"uri": "http://lserver1.local:3000/",
			"useBasicParsing": true,
			"useDefaultCredentials": false
		}
	],
	"ScheduledTasks": [
		{
			"friendlyName": "Notification Task",
			"taskpath": "\\Microsoft\\Windows\\WwanSvc\\NotificationTask"
		}
	]
}
